defaults:
  - _self_

num_envs: 2
freq: 40 # can onl be divisible by 20
camera_follow: True
env_name: warehouse
# env_name: full-warehouse

sensor:
  enable_lidar: True
  enable_camera: True
  color_image: True
  depth_image: True
  semantic_segmentation: True
  camera:
    pos: [0.5, 0.0, 0.1]
    rot: [1.0, 0.0, 0.0, 0.0]
  lidar:
    pos: [0.0, 0.0, 0.25]
    rot: [1.0, 0.0, 0.0, 0.0]

sim_app:
  anti_aliasing: 0
  width: 1280
  height: 720
  hide_ui: False

agent_cfg_path: "config/agent.yaml"